print()
print("In PyCharm, right-click in this window and select   'Run test_my_setup'")
print("If this message shows up in a window, your Python setup is OK.")
print()
print("Then, add a   print   statement of your own (anything is fine)")
print("Then, from the VCS menu (at the top), select Commit, then the Commit and Push option")
print("If you get a message that says your Push was successful, your GIT setup is also OK.")